name: ‚ùå Delete FireFly AWS Stack

on:
  workflow_dispatch

jobs:
  delete-lambdas:
    environment: production
    name: Delete Lambda Stacks
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete func-api-health
        run: |
          sam delete \
            --stack-name firefly-func-api-health \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

      - name: Delete func-s3-firmware-uploaded
        run: |
          sam delete \
            --stack-name firefly-func-s3-firmware-uploaded \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

      - name: Delete func-s3-firmware-deleted
        run: |
          sam delete \
            --stack-name firefly-func-s3-firmware-deleted \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

  delete-api:
    environment: production
    name: Delete API Stack
    runs-on: ubuntu-latest
    needs: delete-lambdas

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete API Gateway + Custom Domain
        run: |
          sam delete \
            --stack-name firefly-api-stack \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

  delete-s3:
    environment: production
    name: Delete S3 Firmware Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete S3 Bucket for Firmware stack
        run: |
          sam delete \
            --stack-name firefly-s3-firmware-bucket-stack \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts