name: ðŸš€ Deploy FireFly AWS Infrastructure

on:
  workflow_dispatch

jobs:

  deploy-dynamodb-firmware:
    environment: production
    name: Deploy DynamoDB Firmware Table
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build DynamoDB SAM application
        run: sam build --template-file Cloud/templates/dynamodb-table-firmware.yaml

      - name: Deploy DynamoDB table
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/templates/dynamodb-table-firmware.yaml \
            --stack-name firefly-dynamodb-firmware \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              DynamoDbFirmwareTableName=${{ vars.DYNAMODB_FIRMWARE_TABLE_NAME }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}

  deploy-api-gateway:
    environment: production
    name: Deploy API Gateway + ACM
    runs-on: ubuntu-latest

    outputs: 
      ApiId: ${{ steps.get-api-id.outputs.apiid }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build API SAM application
        run: sam build --template-file Cloud/templates/api-gateway.yaml

      - name: Deploy API Gateway + Custom Domain
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/templates/api-gateway.yaml \
            --stack-name firefly-api-gateway \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              ApiDomainName=${{ vars.API_DOMAIN_NAME }} \
              CertificateDomainName=${{ vars.CERTIFICATE_DOMAIN_NAME }} \
              HostedZoneId=${{ secrets.HOSTED_ZONE_ID }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}
            
      - name: Retrieve API ID
        id: get-api-id
        run: |
          apiid=$(aws cloudformation describe-stacks --stack-name firefly-api-gateway \
            --query "Stacks[0].Outputs[?OutputKey=='ApiId'].OutputValue" --output text)
          echo "apiid=$apiid" >> $GITHUB_OUTPUT


  deploy-func-api-health:
    environment: production
    name: Deploy func-api-health
    runs-on: ubuntu-latest
    needs: deploy-api-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build Health API stack
        run: sam build --template-file Cloud/lambdas/func-api-health/template.yaml

      - name: Deploy Health API stack
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/lambdas/func-api-health/template.yaml \
            --stack-name firefly-func-api-health \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              ApiId=${{ needs.deploy-api-gateway.outputs.ApiId }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}

  deploy-func-s3-firmware-uploaded:
    environment: production
    name: Deploy func-s3-firmware-uploaded
    runs-on: ubuntu-latest
    needs: deploy-dynamodb-firmware

    outputs:
      UploadLambdaArn: ${{ steps.get-upload-arn.outputs.uploadarn }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build upload Lambda
        run: sam build --template-file Cloud/lambdas/func-s3-firmware-uploaded/template.yaml

      - name: Deploy upload Lambda
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/lambdas/func-s3-firmware-uploaded/template.yaml \
            --stack-name firefly-func-s3-firmware-uploaded \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              FirmwareBucketName=${{ secrets.S3_FIRMWARE_BUCKET_NAME }} \
              DynamoDbFirmwareTableName=${{ vars.DYNAMODB_FIRMWARE_TABLE_NAME }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}

      - name: Retrieve Upload Lambda ARN
        id: get-upload-arn
        run: |
          arn=$(aws cloudformation describe-stacks --stack-name firefly-func-s3-firmware-uploaded \
            --query "Stacks[0].Outputs[?OutputKey=='FuncS3FirmwareUploadedArn'].OutputValue" --output text)
          echo "uploadarn=$arn" >> $GITHUB_OUTPUT

  deploy-func-s3-firmware-deleted:
    environment: production
    name: Deploy func-s3-firmware-deleted
    runs-on: ubuntu-latest
    needs: deploy-dynamodb-firmware

    outputs:
      DeleteLambdaArn: ${{ steps.get-delete-arn.outputs.deletearn }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build delete Lambda
        run: sam build --template-file Cloud/lambdas/func-s3-firmware-deleted/template.yaml

      - name: Deploy delete Lambda
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/lambdas/func-s3-firmware-deleted/template.yaml \
            --stack-name firefly-func-s3-firmware-deleted \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              DynamoDbFirmwareTableName=${{ vars.DYNAMODB_FIRMWARE_TABLE_NAME }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}

      - name: Retrieve Delete Lambda ARN
        id: get-delete-arn
        run: |
          arn=$(aws cloudformation describe-stacks --stack-name firefly-func-s3-firmware-deleted \
            --query "Stacks[0].Outputs[?OutputKey=='FuncS3FirmwareDeletedArn'].OutputValue" --output text)
          echo "deletearn=$arn" >> $GITHUB_OUTPUT

  deploy-s3-bucket-firmware:
    environment: production
    name: Deploy S3 Bucket for Firmware
    runs-on: ubuntu-latest
    needs:
      - deploy-func-s3-firmware-uploaded
      - deploy-func-s3-firmware-deleted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build S3 bucket SAM application
        run: sam build --template-file Cloud/templates/s3-bucket-firmware.yaml

      - name: Deploy S3 bucket
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file Cloud/templates/s3-bucket-firmware.yaml \
            --stack-name firefly-s3-bucket-firmware \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              BucketName=${{ secrets.S3_FIRMWARE_BUCKET_NAME }} \
              FirmwareUploadLambdaArn=${{ needs.deploy-func-s3-firmware-uploaded.outputs.UploadLambdaArn }} \
              FirmwareDeleteLambdaArn=${{ needs.deploy-func-s3-firmware-deleted.outputs.DeleteLambdaArn }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}