name: Delete AWS SAM Stack

on:
  workflow_dispatch:

jobs:
  delete-s3-stack:

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Delete S3 Bucket for Firmware stack
        run: |
          sam delete \
            --stack-name sam-s3-firmware-bucket-stack \
            --region ${{ vars.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

  delete-api-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Delete API Gateway + Custom Domain
        run: |
          sam delete \
            --stack-name sam-api-stack \
            --region ${{ vars.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts