name: ‚ùå Delete FireFly AWS Stack

on:
  workflow_dispatch

jobs:
  delete-s3:
    if: github.actor == 'BrentIO'
    environment: production

    name: Delete S3 Firmware Bucket

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete S3 Bucket for Firmware stack
        run: |
          sam delete \
            --stack-name firefly-s3-firmware-bucket-stack \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

  delete-api:
    if: github.actor == 'BrentIO'
    environment: production

    name: Delete API Stack
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete API Gateway + Custom Domain
        run: |
          sam delete \
            --stack-name firefly-api-stack \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts

  delete-lambdas:
    if: github.actor == 'BrentIO'
    environment: production

    name: Delete Lambda Stack
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete Lambda stack
        run: |
          sam delete \
            --stack-name firefly-lambda-stack \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
              --no-prompts